import Sidebar from "./sidebar";
import './globals.css'

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-row w-full h-full">
        <div className="">
          <Sidebar />
        </div>
        <div className="w-full bg-[#000329] h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
